### ISSUE TITLE
Get SSL working to allow app to use django app api

### ISSUE THREAD

**Issue by hklebs** [justbeneu/JustBe-Android#5]

**Comment by ColinKohler** [comment]
Just making a note that this is the highest priority item we have at the moment. It blocks all other tickets involving pulling info from the database.

**Comment by EdHurtig** [comment]
Acked

**Comment by EdHurtig** [comment]
Noting the follow SO Article: http://stackoverflow.com/questions/16504527/how-to-do-an-https-post-from-android.  States that we don't need to use custom cert stores.

**Comment by EdHurtig** [comment]
Ah wait but `https://www.secure-headland-8362.herokuapp.com/api/v1/create_user/` is invalid

**Comment by EdHurtig** [comment]
That is a bigger issue

**Comment by EdHurtig** [comment]
Seems like it is working... getting stange error:

```
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime: FATAL EXCEPTION: main
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime: Process: justbe.mindfulnessapp, PID: 1815
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime: java.lang.IllegalStateException: Could not find method submitPressed(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatButton with id 'submitButton'
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at android.support.v7.internal.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:310)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at android.support.v7.internal.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:269)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at android.view.View.performClick(View.java:5198)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:21147)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-18 12:53:42.286 1815-1815/justbe.mindfulnessapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ColinKohler** [comment]
When I removed the 'www' I didn't get any errors but it doesn't seem to do anything... No idea why we arn't getting the same error unless you changed something else?

**Comment by EdHurtig** [comment]
Will look a bit closer

**Comment by ColinKohler** [comment]
Any updates on this?

**Comment by EdHurtig** [comment]
See PR
